import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../data/repositories/health_alert_repository.dart';
import '../data/repositories/follow_request_repository.dart';
import '../data/services/health_connect_service.dart';
import '../data/services/health_monitoring_service.dart';
import '../data/models/health_alert_model.dart';

final healthAlertRepositoryProvider = Provider<HealthAlertRepository>((ref) {
  return HealthAlertRepository();
});

final healthConnectServiceProvider = Provider<GoogleFitService>((ref) {
  return GoogleFitService();
});

final localNotificationsProvider = Provider<FlutterLocalNotificationsPlugin>((
  ref,
) {
  return FlutterLocalNotificationsPlugin();
});

final healthMonitoringServiceProvider = Provider<HealthMonitoringService>((
  ref,
) {
  return HealthMonitoringService(
    alertRepository: ref.watch(healthAlertRepositoryProvider),
    healthService: ref.watch(healthConnectServiceProvider),
    notifications: ref.watch(localNotificationsProvider),
  );
});

/// Start health monitoring using existing PassiveListener
Future<void> startHealthMonitoring(String userId) async {
  // PassiveListener already running - just enable AI checks
  final prefs = await SharedPreferences.getInstance();
  await prefs.setBool('ai_monitoring_enabled_$userId', true);
  await prefs.setInt(
    'last_ai_check_$userId',
    DateTime.now().millisecondsSinceEpoch,
  );

  // Run immediate check
  await runImmediateHealthCheck(userId);
}

/// Stop health monitoring
Future<void> stopHealthMonitoring() async {
  final prefs = await SharedPreferences.getInstance();
  final keys = prefs.getKeys().where(
    (k) => k.startsWith('ai_monitoring_enabled_'),
  );
  for (final key in keys) {
    await prefs.remove(key);
  }
}

/// Run immediate health check
Future<Map<String, dynamic>> runImmediateHealthCheck(String userId) async {
  final container = ProviderContainer();
  final service = container.read(healthMonitoringServiceProvider);

  try {
    final result = await service.monitorUser(userId);
    return result;
  } catch (e) {
    print('[HealthMonitoring] Check failed: $e');
    rethrow;
  } finally {
    container.dispose();
  }
}

/// Check if should run AI monitoring (every 6 hours)
Future<bool> shouldRunAIMonitoring(String userId) async {
  final prefs = await SharedPreferences.getInstance();
  if (!(prefs.getBool('ai_monitoring_enabled_$userId') ?? false)) return false;

  final lastCheck = prefs.getInt('last_ai_check_$userId') ?? 0;
  final now = DateTime.now().millisecondsSinceEpoch;

  if (now - lastCheck >= 6 * 60 * 60 * 1000) {
    await prefs.setInt('last_ai_check_$userId', now);
    return true;
  }
  return false;
}

/// Provider for doctor's patient alerts
final doctorPatientAlertsProvider = FutureProvider.family
    .autoDispose<List<HealthAlert>, String>((ref, doctorId) async {
      final followRepo = FollowRequestRepository();
      final alertRepo = HealthAlertRepository();

      // Get list of patients followed by this doctor
      final patientIds = await followRepo.getAcceptedPatientIdsForDoctor(
        doctorId,
      );

      if (patientIds.isEmpty) return [];

      // Get recent abnormal alerts from these patients
      return await alertRepo.getRecentAbnormalAlertsForPatients(
        patientIds,
        hoursBack: 24,
        limit: 10,
      );
    });

/// Create test alert data for debugging (DEVELOPMENT ONLY)
Future<void> createTestAlert(String userId) async {
  final repository = HealthAlertRepository();

  final testAlert = HealthAlert(
    id: '', // Will be generated by Firestore
    userId: userId,
    timestamp: DateTime.now().subtract(const Duration(hours: 2)),
    level: AlertLevel.warning,
    message: 'Phát hiện dấu hiệu bất thường về nhịp tim và SpO2',
    prediction: HealthPrediction(
      probabilityNormal: 0.15,
      probabilityWarning: 0.65,
      probabilityDanger: 0.20,
    ),
    metrics: {
      'heart_rate': 105.0,
      'spo2': 92.0,
      'sleep_duration': 5.5,
      'sleep_efficiency': 75.0,
    },
    isRead: false,
    isDoctorNotified: false,
  );

  try {
    await repository.saveAlert(testAlert);
    print('[HealthMonitoring] Test alert created successfully');

    // Send notification for test alert
    await _sendPatientNotification(
      userId: userId,
      alertLevel: testAlert.level,
      message: testAlert.message ?? 'Đã tạo cảnh báo test',
    );
    print('[HealthMonitoring] Test notification sent');
  } catch (e) {
    print('[HealthMonitoring] Failed to create test alert: $e');
  }
}

/// Send notification to patient
Future<void> _sendPatientNotification({
  required String userId,
  required AlertLevel alertLevel,
  required String message,
}) async {
  try {
    final String title;
    switch (alertLevel) {
      case AlertLevel.normal:
        title = '✅ Kết quả phân tích sức khỏe';
        break;
      case AlertLevel.warning:
        title = '⚠️ Cảnh báo sức khỏe';
        break;
      case AlertLevel.danger:
        title = '🚨 Cảnh báo sức khỏe khẩn cấp';
        break;
    }

    await FlutterLocalNotificationsPlugin().show(
      DateTime.now().millisecondsSinceEpoch.remainder(100000),
      title,
      message,
      NotificationDetails(
        android: AndroidNotificationDetails(
          'health_monitoring',
          'Theo dõi sức khỏe',
          channelDescription: 'Thông báo về tình trạng sức khỏe',
          importance: Importance.high,
          priority: Priority.high,
          icon: '@drawable/ic_stat_notify',
        ),
      ),
    );
  } catch (e) {
    print('[HealthMonitoring] Failed to send notification: $e');
  }
}
